// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgt5he_6J5ORjfES67EFWccS9dTKB-wi4',
    appId: '1:164754565833:web:52891189ee2426427dfb18',
    messagingSenderId: '164754565833',
    projectId: 'findyourpet-b0280',
    authDomain: 'findyourpet-b0280.firebaseapp.com',
    storageBucket: 'findyourpet-b0280.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-HvCPOSnFHv4UWnZixxaBdjs-vhhCZpA',
    appId: '1:164754565833:android:d0f4ebc52f0811a77dfb18',
    messagingSenderId: '164754565833',
    projectId: 'findyourpet-b0280',
    storageBucket: 'findyourpet-b0280.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHx6GLMkNVLbb8NYDn-cXK4R8vxxFaIAc',
    appId: '1:164754565833:ios:0f9e884e18e238f17dfb18',
    messagingSenderId: '164754565833',
    projectId: 'findyourpet-b0280',
    storageBucket: 'findyourpet-b0280.appspot.com',
    iosBundleId: 'com.example.findYourPet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHx6GLMkNVLbb8NYDn-cXK4R8vxxFaIAc',
    appId: '1:164754565833:ios:0f9e884e18e238f17dfb18',
    messagingSenderId: '164754565833',
    projectId: 'findyourpet-b0280',
    storageBucket: 'findyourpet-b0280.appspot.com',
    iosBundleId: 'com.example.findYourPet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgt5he_6J5ORjfES67EFWccS9dTKB-wi4',
    appId: '1:164754565833:web:8884b5384bedfc057dfb18',
    messagingSenderId: '164754565833',
    projectId: 'findyourpet-b0280',
    authDomain: 'findyourpet-b0280.firebaseapp.com',
    storageBucket: 'findyourpet-b0280.appspot.com',
  );
}
